mysql:
  image: mysql:8.0
  database: petclinicdb
  credentials:
    username: petuser
    password: Mohan@123
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

spring:
  repo: "44.245.219.19/images.petclinic"
  image: petclinic
  tag: v1
  containerPort: 8080
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
mountPath: /opt/petclinic/config
confFile: application.properties

artifactory:
  server: "44.245.219.19:8082/"
  username: "admin"
  password: ""